apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <html>
      <head><title>Welcome to Nginx!</title></head>
      <body>
        <h1>Hello from Kubernetes Nginx with PVC!</h1>
      </body>
    </html>
